const buyurtmaMagazinData = [
  {
    maxsulot_nomi: "Telefon",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "20sm * 40sm",
    maxsulot_soni: "70ta",
    holati: "Yetkazildi",
  },
  {
    maxsulot_nomi: "Kompyuter",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "32dyum",
    maxsulot_soni: "120ta",
    holati: "Yetkazilyapti",
  },
  {
    maxsulot_nomi: "Televizor",
    maxsulot_rangi: "Oq",
    maxsulot_olchami: "42dyum",
    maxsulot_soni: "200ta",
    holati: "Qabul qilindi",
  },
  {
    maxsulot_nomi: "BMW I8",
    maxsulot_rangi: "Qizil",
    maxsulot_olchami: "300sm",
    maxsulot_soni: "20ta",
    holati: "Yetkazilmoqda",
  },
  {
    maxsulot_nomi: "Vertalyot",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "600sm",
    maxsulot_soni: "1ta",
    holati: "Yaratildi",
  },
  {
    maxsulot_nomi: "Telefon",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "20sm * 40sm",
    maxsulot_soni: "70ta",
    holati: "Yetkazildi",
  },
  {
    maxsulot_nomi: "Kompyuter",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "32dyum",
    maxsulot_soni: "120ta",
    holati: "Yetkazilyapti",
  },
  {
    maxsulot_nomi: "Televizor",
    maxsulot_rangi: "Oq",
    maxsulot_olchami: "42dyum",
    maxsulot_soni: "200ta",
    holati: "Qabul qilindi",
  },
  {
    maxsulot_nomi: "BMW I8",
    maxsulot_rangi: "Qizil",
    maxsulot_olchami: "300sm",
    maxsulot_soni: "20ta",
    holati: "Yetkazilmoqda",
  },
  {
    maxsulot_nomi: "Vertalyot",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "600sm",
    maxsulot_soni: "1ta",
    holati: "Yaratildi",
  },
  {
    maxsulot_nomi: "Telefon",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "20sm * 40sm",
    maxsulot_soni: "70ta",
    holati: "Yetkazildi",
  },
  {
    maxsulot_nomi: "Kompyuter",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "32dyum",
    maxsulot_soni: "120ta",
    holati: "Yetkazilyapti",
  },
  {
    maxsulot_nomi: "Televizor",
    maxsulot_rangi: "Oq",
    maxsulot_olchami: "42dyum",
    maxsulot_soni: "200ta",
    holati: "Qabul qilindi",
  },
  {
    maxsulot_nomi: "BMW I8",
    maxsulot_rangi: "Qizil",
    maxsulot_olchami: "300sm",
    maxsulot_soni: "20ta",
    holati: "Yetkazilmoqda",
  },
  {
    maxsulot_nomi: "Vertalyot",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "600sm",
    maxsulot_soni: "1ta",
    holati: "Yaratildi",
  },
  {
    maxsulot_nomi: "Telefon",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "20sm * 40sm",
    maxsulot_soni: "70ta",
    holati: "Yetkazildi",
  },
  {
    maxsulot_nomi: "Kompyuter",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "32dyum",
    maxsulot_soni: "120ta",
    holati: "Yetkazilyapti",
  },
  {
    maxsulot_nomi: "Televizor",
    maxsulot_rangi: "Oq",
    maxsulot_olchami: "42dyum",
    maxsulot_soni: "200ta",
    holati: "Qabul qilindi",
  },
  {
    maxsulot_nomi: "BMW I8",
    maxsulot_rangi: "Qizil",
    maxsulot_olchami: "300sm",
    maxsulot_soni: "20ta",
    holati: "Yetkazilmoqda",
  },
  {
    maxsulot_nomi: "Vertalyot",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "600sm",
    maxsulot_soni: "1ta",
    holati: "Yaratildi",
  },
  {
    maxsulot_nomi: "Telefon",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "20sm * 40sm",
    maxsulot_soni: "70ta",
    holati: "Yetkazildi",
  },
  {
    maxsulot_nomi: "Kompyuter",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "32dyum",
    maxsulot_soni: "120ta",
    holati: "Yetkazilyapti",
  },
  {
    maxsulot_nomi: "Televizor",
    maxsulot_rangi: "Oq",
    maxsulot_olchami: "42dyum",
    maxsulot_soni: "200ta",
    holati: "Qabul qilindi",
  },
  {
    maxsulot_nomi: "BMW I8",
    maxsulot_rangi: "Qizil",
    maxsulot_olchami: "300sm",
    maxsulot_soni: "20ta",
    holati: "Yetkazilmoqda",
  },
  {
    maxsulot_nomi: "Vertalyot",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "600sm",
    maxsulot_soni: "1ta",
    holati: "Yaratildi",
  },
  {
    maxsulot_nomi: "Telefon",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "20sm * 40sm",
    maxsulot_soni: "70ta",
    holati: "Yetkazildi",
  },
  {
    maxsulot_nomi: "Kompyuter",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "32dyum",
    maxsulot_soni: "120ta",
    holati: "Yetkazilyapti",
  },
  {
    maxsulot_nomi: "Televizor",
    maxsulot_rangi: "Oq",
    maxsulot_olchami: "42dyum",
    maxsulot_soni: "200ta",
    holati: "Qabul qilindi",
  },
  {
    maxsulot_nomi: "BMW I8",
    maxsulot_rangi: "Qizil",
    maxsulot_olchami: "300sm",
    maxsulot_soni: "20ta",
    holati: "Yetkazilmoqda",
  },
  {
    maxsulot_nomi: "Vertalyot",
    maxsulot_rangi: "Qora",
    maxsulot_olchami: "600sm",
    maxsulot_soni: "1ta",
    holati: "Yaratildi",
  }
];

export default buyurtmaMagazinData;