const tushumlarData = [
    {
      maxsulot_nomi: "IPhone 14 Pro MAX",
      summa: "120000$",
      valuta: "USD",
      sana: "17.05.2023",
      dokon_nomi: "Apple Inc.",
    },
    {
      maxsulot_nomi: "BMW I8",
      summa: "7200000$",
      valuta: "USD",
      sana: "09.06.2023",
      dokon_nomi: "BMW Inc.",
    },
    {
      maxsulot_nomi: "Mercedes Bens",
      summa: "8900000$",
      valuta: "USD",
      sana: "12.07.2022",
      dokon_nomi: "Mercedes-Benz",
    },
    {
      maxsulot_nomi: "IPhone 14 Pro MAX",
      summa: "120000$",
      valuta: "USD",
      sana: "17.05.2023",
      dokon_nomi: "Apple Inc.",
    },
    {
      maxsulot_nomi: "BMW I8",
      summa: "7200000$",
      valuta: "USD",
      sana: "09.06.2023",
      dokon_nomi: "BMW Inc.",
    },
    {
      maxsulot_nomi: "Mercedes Bens",
      summa: "8900000$",
      valuta: "USD",
      sana: "12.07.2022",
      dokon_nomi: "Mercedes-Benz",
    },
    {
      maxsulot_nomi: "IPhone 14 Pro MAX",
      summa: "120000$",
      valuta: "USD",
      sana: "17.05.2023",
      dokon_nomi: "Apple Inc.",
    },
    {
      maxsulot_nomi: "BMW I8",
      summa: "7200000$",
      valuta: "USD",
      sana: "09.06.2023",
      dokon_nomi: "BMW Inc.",
    },
    {
      maxsulot_nomi: "Mercedes Bens",
      summa: "8900000$",
      valuta: "USD",
      sana: "12.07.2022",
      dokon_nomi: "Mercedes-Benz",
    },
    {
      maxsulot_nomi: "IPhone 14 Pro MAX",
      summa: "120000$",
      valuta: "USD",
      sana: "17.05.2023",
      dokon_nomi: "Apple Inc.",
    },
    {
      maxsulot_nomi: "BMW I8",
      summa: "7200000$",
      valuta: "USD",
      sana: "09.06.2023",
      dokon_nomi: "BMW Inc.",
    },
    {
      maxsulot_nomi: "Mercedes Bens",
      summa: "8900000$",
      valuta: "USD",
      sana: "12.07.2022",
      dokon_nomi: "Mercedes-Benz",
    },
    {
        maxsulot_nomi: "IPhone 14 Pro MAX",
        summa: "120000$",
        valuta: "USD",
        sana: "17.05.2023",
        dokon_nomi: "Apple Inc.",
      },
      {
        maxsulot_nomi: "BMW I8",
        summa: "7200000$",
        valuta: "USD",
        sana: "09.06.2023",
        dokon_nomi: "BMW Inc.",
      },
      {
        maxsulot_nomi: "Mercedes Bens",
        summa: "8900000$",
        valuta: "USD",
        sana: "12.07.2022",
        dokon_nomi: "Mercedes-Benz",
      },
      {
        maxsulot_nomi: "IPhone 14 Pro MAX",
        summa: "120000$",
        valuta: "USD",
        sana: "17.05.2023",
        dokon_nomi: "Apple Inc.",
      },
      {
        maxsulot_nomi: "BMW I8",
        summa: "7200000$",
        valuta: "USD",
        sana: "09.06.2023",
        dokon_nomi: "BMW Inc.",
      },
      {
        maxsulot_nomi: "Mercedes Bens",
        summa: "8900000$",
        valuta: "USD",
        sana: "12.07.2022",
        dokon_nomi: "Mercedes-Benz",
      },
      {
        maxsulot_nomi: "IPhone 14 Pro MAX",
        summa: "120000$",
        valuta: "USD",
        sana: "17.05.2023",
        dokon_nomi: "Apple Inc.",
      },
      {
        maxsulot_nomi: "BMW I8",
        summa: "7200000$",
        valuta: "USD",
        sana: "09.06.2023",
        dokon_nomi: "BMW Inc.",
      },
      {
        maxsulot_nomi: "Mercedes Bens",
        summa: "8900000$",
        valuta: "USD",
        sana: "12.07.2022",
        dokon_nomi: "Mercedes-Benz",
      },
      {
        maxsulot_nomi: "IPhone 14 Pro MAX",
        summa: "120000$",
        valuta: "USD",
        sana: "17.05.2023",
        dokon_nomi: "Apple Inc.",
      },
      {
        maxsulot_nomi: "BMW I8",
        summa: "7200000$",
        valuta: "USD",
        sana: "09.06.2023",
        dokon_nomi: "BMW Inc.",
      },
      {
        maxsulot_nomi: "Mercedes Bens",
        summa: "8900000$",
        valuta: "USD",
        sana: "12.07.2022",
        dokon_nomi: "Mercedes-Benz",
      },
      {
        maxsulot_nomi: "IPhone 14 Pro MAX",
        summa: "120000$",
        valuta: "USD",
        sana: "17.05.2023",
        dokon_nomi: "Apple Inc.",
      },
      {
        maxsulot_nomi: "BMW I8",
        summa: "7200000$",
        valuta: "USD",
        sana: "09.06.2023",
        dokon_nomi: "BMW Inc.",
      },
      {
        maxsulot_nomi: "Mercedes Bens",
        summa: "8900000$",
        valuta: "USD",
        sana: "12.07.2022",
        dokon_nomi: "Mercedes-Benz",
      },
      {
        maxsulot_nomi: "IPhone 14 Pro MAX",
        summa: "120000$",
        valuta: "UZS",
        sana: "17.05.2023",
        dokon_nomi: "Apple Inc.",
      },
      {
        maxsulot_nomi: "BMW I8",
        summa: "7200000$",
        valuta: "USD",
        sana: "09.06.2023",
        dokon_nomi: "BMW Inc.",
      },
      {
        maxsulot_nomi: "Mercedes Bens",
        summa: "8900000$",
        valuta: "USD",
        sana: "12.07.2022",
        dokon_nomi: "Mercedes-Benz",
      },
      {
        maxsulot_nomi: "IPhone 14 Pro MAX",
        summa: "120000$",
        valuta: "SOM",
        sana: "17.05.2023",
        dokon_nomi: "Apple Inc.",
      },
      {
        maxsulot_nomi: "BMW I8",
        summa: "7200000$",
        valuta: "USD",
        sana: "09.06.2023",
        dokon_nomi: "BMW Inc.",
      },
      {
        maxsulot_nomi: "Mercedes Bens",
        summa: "8900000$",
        valuta: "Evro",
        sana: "12.07.2022",
        dokon_nomi: "Mercedes-Benz",
      },
      {
        maxsulot_nomi: "IPhone 14 Pro MAX",
        summa: "120000$",
        valuta: "Yuan",
        sana: "17.05.2023",
        dokon_nomi: "Apple Inc.",
      },
      {
        maxsulot_nomi: "BMW I8",
        summa: "7200000$",
        valuta: "USD",
        sana: "09.06.2023",
        dokon_nomi: "BMW Inc.",
      },
      {
        maxsulot_nomi: "Mercedes Bens",
        summa: "8900000$",
        valuta: "UZS",
        sana: "12.07.2022",
        dokon_nomi: "Mercedes-Benz",
      },
      
  ];
  
  
  export default tushumlarData;